---
title: "R Notebook"
output: html_notebook
---

```{bash, eval=FALSE}

## download hapmap genotypes

mkdir /home/haky/IntroStatGen/data/
mkdir /home/haky/IntroStatGen/data/hapmap

wget https://storage.googleapis.com/introstatgen/hapmap.bed /home/haky/IntroStatGen/data/hapmap
wget https://storage.googleapis.com/introstatgen/hapmap.bim /home/haky/IntroStatGen/data/hapmap
wget https://storage.googleapis.com/introstatgen/hapmap.fam /home/haky/IntroStatGen/data/hapmap

wget ftp://ftp.ncbi.nlm.nih.gov/hapmap/phase_3/relationships_w_pops_051208.txt /home/haky/IntroStatGen/data/hapmap/

## maf 

```

```{r, echo=FALSE, eval=FALSE}
if(F)
{## run plink to get maf
system(paste0(bin.dir,"plink --bfile ", data.dir,"hapmap --freq --out ",out.dir, "hapmap"))
mafdata = read_table(paste0(out.dir, "hapmap.frq"))
hist(mafdata$MAF)

## use plink to generate subset with MAF > 0.05
system(paste0(bin.dir,"plink --bfile ", data.dir,"hapmap --make-bed --maf 0.05 --chr 1-22 --out ",data.dir, "hapmap-common"))
}

```

```{r}
library(tidyverse)
data.dir = "/home/haky/IntroStatGen/data/hapmap/"
bin.dir = "/home/haky/IntroStatGen/bin/"
out.dir ="/home/haky/IntroStatGen/out/"
gist.dir = "/home/haky/IntroStatGen/repo-IntroStatGen/gists/"

```


```{r}

plinkname = paste0(bin.dir,"plink")
bedheader = paste0(data.dir,"hapmap-common")

## subset CEU, YRI, ASN
popinfo = read_tsv(paste0(data.dir,"relationships_w_pops_051208.txt"))
popinfo %>% filter(population %in% c("CEU","YRI","CHB","JPT")) %>% write_tsv(paste0(data.dir,"hapmap2.list.txt"))

comm = paste0(plinkname, " --bfile ", data.dir, "hapmap-common ", " --make-bed --keep ", data.dir,"hapmap2.list.txt ", " --maf 0.05 --out ", data.dir, "hapmap2-common")
print(comm)
system(comm)


##left and right plink files
comm = paste0(plinkname, " --bfile ", data.dir, "hapmap-common ", " --make-bed ", " --maf 0.05", " --chr 1-8 " , " --out ", data.dir, "hapmap-common-left")
print(comm)
system(comm)

comm = paste0(plinkname, " --bfile ", data.dir, "hapmap-common ", " --make-bed ",  " --maf 0.05", " --chr 9-22 " , " --out ", data.dir, "hapmap-common-right")
print(comm)
system(comm)

##hapmap2 left and right plink files
comm = paste0(plinkname, " --bfile ", data.dir, "hapmap-common ", " --make-bed --keep ", data.dir,"hapmap2.list.txt ", " --maf 0.05", " --chr 1-10 " , " --out ", data.dir, "hapmap2-common-left")
print(comm)
system(comm)

comm = paste0(plinkname, " --bfile ", data.dir, "hapmap-common ", " --make-bed --keep ", data.dir,"hapmap2.list.txt ", " --maf 0.05", " --chr 11-22 " , " --out ", data.dir, "hapmap2-common-right")
print(comm)
system(comm)

```

EURsubset
```{r}

## subset CEU, TSI
popinfo = read_tsv(paste0(data.dir,"relationships_w_pops_051208.txt"))
popinfo %>% filter(population %in% c("CEU","TSI")) %>% write_tsv(paste0(data.dir,"EUR.txt"))

comm = paste0(plinkname, " --bfile ", data.dir, "hapmap-common ", " --make-bed --keep ", data.dir,"EUR.txt ", " --maf 0.05 --out ", data.dir, "EUR-common")
print(comm)
system(comm)


##left and right plink files
comm = paste0(plinkname, " --bfile ", data.dir, "EUR-common ", " --make-bed ", " --maf 0.05", " --chr 1-8 " , " --out ", data.dir, "EUR-common-left")
print(comm)
system(comm)

comm = paste0(plinkname, " --bfile ", data.dir, "EUR-common ", " --make-bed ",  " --maf 0.05", " --chr 9-22 " , " --out ", data.dir, "EUR-common-right")
print(comm)
system(comm)

```
Founders only
```{r}

## subset founders

comm = paste0(plinkname, " --bfile ", data.dir, "hapmap-common ", " --make-bed --filter-founders ", " --maf 0.05 --out ", data.dir, "founders-common")
print(comm)
system(comm)


##left and right plink files
comm = paste0(plinkname, " --bfile ", data.dir, "founders-common ", " --make-bed  --filter-founders ", " --maf 0.05", " --chr 1-8 " , " --out ", data.dir, "founders-common-left")
print(comm)
system(comm)

comm = paste0(plinkname, " --bfile ", data.dir, "founders-common ", " --make-bed  --filter-founders ",  " --maf 0.05", " --chr 9-22 " , " --out ", data.dir, "founders-common-right")
print(comm)
system(comm)

```

