---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


---------------


```{r}
# ## identify families
# pcplink %>% count(FID) %>% filter(n>2) %>% inner_join(popinfo,by=c("FID"="FID")) %>% head(10)

# ## label 13291, 1330
# pcplink %>% filter(population %in% c("CEU","TSI")) %>% ggplot(aes(PC1,PC2,col=population)) + geom_point() + geom_label_repel(data=pcplink %>% filter(FID %in% c("13291") ),aes(PC1,PC2,label=IID))
# ## Why are these family members so far appart?

```



Principal component analysis with subset of data in R
```{r}

## get subset of individuals
set.seed(20)
popsubset = popinfo %>% sample_frac(0.10) 
write_tsv(popsubset,path="subset.txt")
## created ped file to read genotype into R (SNPstat package may read bed files directly)

## create text genotype file keeping only non missing genotypes and subset of individuals from subset.txt
system("./plink --bfile hapmapch22 --keep-fam subset.txt  --recodeA  --geno 0 --maf 0.05 --out subset")

## read genoytpe file
geno = read.table("subset.raw",header=T,as.is=T)
## keep genotype only
genomat = geno %>% select(starts_with("rs"))

pca = prcomp(genomat,scale=TRUE,center=TRUE)

```



matching prcomp output and U D V decomposition of svd
```{r}

set.seed(200)
nsam=99;nsnp=498; datamat = matrix(rnorm(nsam*nsnp),nsam,nsnp)
datamat = scale(datamat); ##print(apply(datamat,2,mean)); print(apply(datamat,2,sd))

testpca = prcomp(datamat,center=FALSE,scale=FALSE)
testsvd = svd(datamat)

datamat2 = testpca$x %*% t(testpca$rotation)
datamat3 = testsvd$u %*% diag(testsvd$d) %*% t(testsvd$v)
## testpca$x = testsvd$u %*% diag(testsvd$d)

## DATA = U * D * V'
## pca outcome 
## U columns are eigenvectors of the covariance matrix (data &*& t(data))
##  x = U * D
##  V = rotation

```


Compute pc's of genotype data
```{r}

## add FID and IID to the PC's
pcs = data.frame(geno %>% select(FID, IID),pca$x) 
pcs = popinfo %>% inner_join(pcs,by=c("FID"="FID","IID"="IID"))

pcs %>% ggplot(aes(PC1,PC2,col=population)) + geom_point() 




```